### PR TITLE
Added wasd/WASD keyboard support.

### PR DESCRIPTION
**Pull request by chriszaro**
I added control with WASD keys. To do so, I changed the switch statement with an if statement.

### CODE REVIEW

**Comment by chriszaro** [comment]
@IgorIvanter are you interested in adding features to the game?

**Comment by IgorIvanter** [comment]
Hey @chriszaro, yeah sure! I saw your PR, just didn't have time to check it yet. I wonder how you even found this repo:)

But anyway, if you wanna add some features, feel free to post the requests.

**Comment by chriszaro** [comment]
@IgorIvanter Nice, thanks. I'll send a couple of features I have in mind.

**Comment by IgorIvanter** [comment]
@chriszaro I merged your request. Feel free to add further features. I'll go through everything, but with a bit of delay, because I don't have much time.

**Pull request merged**
