### PR TITLE
Added 4 control buttons around the table of the game.

### PR DESCRIPTION
**Pull request by chriszaro**
They are designed to increase the accessibility of the game. They can be used by disabled people with a head or mouth touch screen stylus. Also, they can be used from users that want to play the game just with the mouse.

### CODE REVIEW

**Comment by chriszaro** [comment]
@IgorIvanter Happy Holidays! Could you give me feedback about the commit you reverted?

**Comment by IgorIvanter** [comment]
Hey man, to be honest I didn't check it the last time, but then I saw it and it doesn't look all that great visually. I mean, the whole game has kinda shitty visuals, but the initial look was bearable I would say. Visuals is tough for coders, me included, and I displayed this project on my portfolio, so I decided to stick to the basic thing.

Sorry for not being clear the first time

**Comment by chriszaro** [comment]
@IgorIvanter Thanks for answering. I understand. Will you check this pull request? The visual theme follows yours this time.

**Comment by IgorIvanter** [comment]
Hey, I saw the request, I'm now in another city without my laptoo, I will return tomorrow and review it

**Comment by chriszaro** [comment]
> Hey man, to be honest I didn't check it the last time, but then I saw it and it doesn't look all that great visually. I mean, the whole game has kinda shitty visuals, but the initial look was bearable I would say. Visuals is tough for coders, me included, and I displayed this project on my portfolio, so I decided to stick to the basic thing. Sorry for not being clear the first time
> […](#)
> On 27. Dec 2022, at 17:34, chriszaro ***@***.***> wrote: ﻿ @IgorIvanter Happy Holidays! Could you give me feedback about the commit you reverted? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Regarding this, do you have any change to suggest or are you not interested at all?

**Pull request closed without merging**
